/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.capgemini.usergegistrationgradle;

import org.junit.Test;

import com.capgemini.userregistrationgradle.CheckoFormat;

import static org.junit.Assert.*;

public class UserRegistrationTestCase {
    @Test public void testSomeLibraryMethod() {
        CheckoFormat classUnderTest = new CheckoFormat();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
