/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.capgemini.usergegistrationgradle;

import org.junit.Test;

import com.capgemini.userregistrationgradle.CheckFormat;

import static org.junit.Assert.*;

public class UserRegistrationTestCase {

}
